### ISSUE TITLE
This simply doesn't work

### ISSUE THREAD

**Issue by msankhala** [VaibhavAcharya/gist-snip#1]
I followed all the steps mentioned by this extension.

1. Installed extension.
2. Authenticated with github by providing a personal access token
3. restarted vs code.
4. started typing with the name of the snippet. Nothing happens.

**Comment by VaibhavAcharya** [comment]
I think this is the case for everyone with a lot of gists.
It loads late because it has to fetch content for every single gist separately.

I will look for a solution to speed this up after holidays. 😅
